# Generated by Django 5.1.6 on 2025-04-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='user',
        ),
    ]
