# Generated by Django 5.1.6 on 2025-04-24 21:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_performance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='performance_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='stats',
            field=models.FileField(blank=True, null=True, upload_to='performance_stats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='performance_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
    ]
